### ISSUE TITLE
Crashes Matrix rooms

### ISSUE THREAD

**Issue by leethax666** [h1ddenpr0cess20/jerkbot-matrix#3]
Running it as per the instructions, other than virtualenv, the bot never joins the room, when exiting the bot, the room crashes and becomes inaccessible to even the creator.

**Comment by h1ddenpr0cess20** [comment]
I have replicated the bug, it appears that if the bot account created the channel and tries to join it, the channel becomes corrupted somehow.  Workaround by creating any new channels with a separate account for now until i figure out why

**Comment by h1ddenpr0cess20** [comment]
confirmed suspicions, bug fixed by commenting out bot.stop()
